[book]
authors = ["Théo Tchilinguirian"]
language = "en"
multilingual = false
src = "src"
title = "A concise guide to distro-hopping"

[output.html]
git-repository-url = "https://github.com/theotchlx/distrohop-guide"

